language: php

sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

before_install:
    - pecl channel-update pecl.php.net
    - if [[ $TRAVIS_PHP_VERSION = '5.6' ]] ; then echo yes | pecl install apcu-4.0.10; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;
    - phpenv config-add ./testing/travis.php.ini
    - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover clover.xml"; fi


install:
    - composer --no-interaction --no-progress install
    - composer show --installed

script: vendor/bin/phpunit
